version: '3'

services:
  postgres:
    build: ./docker
    image: nest-database
    container_name: nest-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - nest-data:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    restart: always

volumes:
  nest-data:
    driver: local
